export type SettingsMap = Record<string, string>;

export const DEFAULT_SETTINGS: SettingsMap = {
  whatsapp: "",
  phone: "",
  email: "",
  instagram: "",
  video_url: "",
  hero_title: "",
  hero_subtitle: "",
  gtm_id: "",
  ga4_measurement_id: "",
  google_ads_id: "",
  google_ads_conversion_label: "",
  google_ads_sale_label: "",
  google_ads_faturado_label: "",
  meta_pixel_id: "",
  meta_test_event_code: "",
  tiktok_pixel_id: "",
  logo_url: "",
  primary_color: "",
  cta_color: "",
  background_color: "",
  border_radius: "",
  section_image_about_primary: "",
  section_image_about_secondary: "",
  section_image_savings: "",
  section_image_hybrid: "",
  section_image_area_primary: "",
  section_image_area_secondary: "",
  landing_content_json: "",
  custom_css: "",
  custom_head_html: "",
  custom_body_html: "",
  custom_block_top_html: "",
  custom_block_bottom_html: "",
};

export const REQUIRED_PUBLIC_SETTING_KEYS = [
  "whatsapp",
  "phone",
  "email",
  "instagram",
  "video_url",
  "hero_title",
  "hero_subtitle",
  "logo_url",
  "primary_color",
  "cta_color",
  "background_color",
  "border_radius",
  "section_image_about_primary",
  "section_image_about_secondary",
  "section_image_savings",
  "section_image_hybrid",
  "section_image_area_primary",
  "section_image_area_secondary",
  "landing_content_json",
] as const;