/** Fontes iniciais monitoradas pelo Radar Editorial. Nenhuma é indispensável. */

export type SeedSource = {
  nome: string;
  dominio: string;
  feed_url: string;
  tipo: "oficial" | "entidade" | "especializado" | "geral";
  categorias: string[];
  prioridade: number;
  autoridade: number;
  metodo: "api" | "rss" | "sitemap" | "pagina";
  adapter: string;
  frequencia_minutos: number;
  politica_uso: string;
};

export const SEED_SOURCES: SeedSource[] = [
  // ---------- OFICIAIS ----------
  {
    nome: "ANEEL — Notícias",
    dominio: "aneel.gov.br",
    feed_url: "https://www.gov.br/aneel/pt-br/assuntos/noticias/RSS",
    tipo: "oficial",
    categorias: ["aneel-regulamentacao", "conta-de-luz", "energia-solar", "mercado-de-energia"],
    prioridade: 100,
    autoridade: 100,
    metodo: "rss",
    adapter: "aneelAdapter",
    frequencia_minutos: 60,
    politica_uso: "Conteúdo público oficial. Uso como fonte primária com crédito e link.",
  },
  {
    nome: "Ministério de Minas e Energia (MME)",
    dominio: "gov.br/mme",
    feed_url: "https://www.gov.br/mme/pt-br/assuntos/noticias/RSS",
    tipo: "oficial",
    categorias: ["aneel-regulamentacao", "mercado-de-energia", "sustentabilidade"],
    prioridade: 100,
    autoridade: 100,
    metodo: "rss",
    adapter: "mmeAdapter",
    frequencia_minutos: 60,
    politica_uso: "Conteúdo público oficial. Uso como fonte primária com crédito e link.",
  },
  {
    nome: "EPE — Empresa de Pesquisa Energética",
    dominio: "epe.gov.br",
    feed_url: "https://www.epe.gov.br/pt/imprensa/noticias/RSS",
    tipo: "oficial",
    categorias: ["mercado-de-energia", "sustentabilidade", "tecnologia"],
    prioridade: 95,
    autoridade: 95,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 180,
    politica_uso: "Estudos e dados públicos. Sempre citar o estudo de origem.",
  },
  {
    nome: "CCEE — Câmara de Comercialização",
    dominio: "ccee.org.br",
    feed_url: "https://www.ccee.org.br/rss/noticias",
    tipo: "oficial",
    categorias: ["mercado-de-energia", "empresas"],
    prioridade: 95,
    autoridade: 95,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 180,
    politica_uso: "Dados públicos de mercado. Citar sempre a CCEE.",
  },
  {
    nome: "ONS — Operador Nacional do Sistema",
    dominio: "ons.org.br",
    feed_url: "https://www.ons.org.br/paginas/rss/noticias.aspx",
    tipo: "oficial",
    categorias: ["mercado-de-energia", "tecnologia"],
    prioridade: 95,
    autoridade: 95,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 240,
    politica_uso: "Dados operativos públicos.",
  },
  {
    nome: "Governo Federal — Energia",
    dominio: "gov.br",
    feed_url: "https://www.gov.br/pt-br/noticias/energia-minerais-e-combustiveis/RSS",
    tipo: "oficial",
    categorias: ["aneel-regulamentacao", "sustentabilidade"],
    prioridade: 100,
    autoridade: 98,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 120,
    politica_uso: "Comunicados oficiais do governo federal.",
  },

  // ---------- ENTIDADES ----------
  {
    nome: "ABSOLAR",
    dominio: "absolar.org.br",
    feed_url: "https://www.absolar.org.br/noticias/feed/",
    tipo: "entidade",
    categorias: ["energia-solar", "aneel-regulamentacao"],
    prioridade: 85,
    autoridade: 85,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 180,
    politica_uso: "Posicionamentos e estatísticas setoriais. Sempre atribuir à entidade.",
  },
  {
    nome: "ABGD — Geração Distribuída",
    dominio: "abgd.com.br",
    feed_url: "https://abgd.com.br/portal/feed/",
    tipo: "entidade",
    categorias: ["energia-solar", "aneel-regulamentacao"],
    prioridade: 80,
    autoridade: 80,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 240,
    politica_uso: "Posicionamentos setoriais de geração distribuída.",
  },
  {
    nome: "ABEEólica",
    dominio: "abeeolica.org.br",
    feed_url: "https://abeeolica.org.br/feed/",
    tipo: "entidade",
    categorias: ["sustentabilidade", "mercado-de-energia"],
    prioridade: 70,
    autoridade: 78,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 360,
    politica_uso: "Contexto de renováveis quando relevante ao setor elétrico.",
  },
  {
    nome: "ABSAE — Armazenamento de Energia",
    dominio: "absae.com.br",
    feed_url: "https://absae.com.br/feed/",
    tipo: "entidade",
    categorias: ["armazenamento-baterias", "tecnologia"],
    prioridade: 80,
    autoridade: 78,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 360,
    politica_uso: "Referência setorial de armazenamento.",
  },
  {
    nome: "ABRACEEL — Mercado Livre",
    dominio: "abraceel.com.br",
    feed_url: "https://abraceel.com.br/feed/",
    tipo: "entidade",
    categorias: ["mercado-de-energia", "empresas"],
    prioridade: 78,
    autoridade: 78,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 360,
    politica_uso: "Posicionamentos sobre mercado livre de energia.",
  },
  {
    nome: "ABVE — Mobilidade Elétrica",
    dominio: "abve.org.br",
    feed_url: "https://abve.org.br/feed/",
    tipo: "entidade",
    categorias: ["mobilidade-eletrica", "tecnologia"],
    prioridade: 70,
    autoridade: 75,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 360,
    politica_uso: "Dados de mercado de veículos elétricos.",
  },

  // ---------- ESPECIALIZADOS ----------
  {
    nome: "Canal Solar",
    dominio: "canalsolar.com.br",
    feed_url: "https://canalsolar.com.br/feed/",
    tipo: "especializado",
    categorias: ["energia-solar", "tecnologia", "armazenamento-baterias"],
    prioridade: 75,
    autoridade: 72,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 60,
    politica_uso: "Somente descoberta de pauta e contexto. Nunca reproduzir texto ou imagem.",
  },
  {
    nome: "pv magazine Brasil",
    dominio: "pv-magazine-brasil.com",
    feed_url: "https://www.pv-magazine-brasil.com/feed/",
    tipo: "especializado",
    categorias: ["energia-solar", "tecnologia", "mercado-de-energia"],
    prioridade: 75,
    autoridade: 74,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 60,
    politica_uso: "Somente descoberta de pauta e contexto. Nunca reproduzir texto ou imagem.",
  },
  {
    nome: "Brasil Energia",
    dominio: "brasilenergia.com.br",
    feed_url: "https://brasilenergia.com.br/feed",
    tipo: "especializado",
    categorias: ["mercado-de-energia", "empresas", "aneel-regulamentacao"],
    prioridade: 72,
    autoridade: 74,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 90,
    politica_uso: "Título e resumo públicos apenas. Não contornar paywall.",
  },
  {
    nome: "MegaWhat",
    dominio: "megawhat.energy",
    feed_url: "https://megawhat.energy/feed",
    tipo: "especializado",
    categorias: ["mercado-de-energia", "aneel-regulamentacao"],
    prioridade: 70,
    autoridade: 72,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 120,
    politica_uso: "Título e resumo públicos apenas. Não contornar paywall.",
  },
  {
    nome: "Portal Solar — Notícias",
    dominio: "portalsolar.com.br",
    feed_url: "https://www.portalsolar.com.br/blog/feed",
    tipo: "especializado",
    categorias: ["energia-solar", "conta-de-luz"],
    prioridade: 65,
    autoridade: 62,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 180,
    politica_uso: "Descoberta de pauta apenas.",
  },
  {
    nome: "Agência Brasil — Economia",
    dominio: "agenciabrasil.ebc.com.br",
    feed_url: "https://agenciabrasil.ebc.com.br/rss/economia/feed.xml",
    tipo: "geral",
    categorias: ["conta-de-luz", "mercado-de-energia"],
    prioridade: 70,
    autoridade: 80,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 120,
    politica_uso: "Veículo público. Filtrar somente assuntos de energia.",
  },
  {
    nome: "InfoMoney — Economia",
    dominio: "infomoney.com.br",
    feed_url: "https://www.infomoney.com.br/feed/",
    tipo: "geral",
    categorias: ["mercado-de-energia", "empresas"],
    prioridade: 55,
    autoridade: 65,
    metodo: "rss",
    adapter: "rssAdapter",
    frequencia_minutos: 180,
    politica_uso: "Descoberta de pauta apenas, filtrada por palavras-chave de energia.",
  },
];
