/**
 * Área de cobertura LZ7 — cidades a até 120 km, em linha reta, de uma das bases:
 * Londrina/PR, Wenceslau Braz/PR e Ponta Grossa/PR.
 *
 * Lista gerada a partir das coordenadas oficiais dos municípios (IBGE).
 * Não editar manualmente: regenerar se o raio ou as bases mudarem.
 */

export const RAIO_COBERTURA_KM = 120;

export const BASES_LZ7 = [
  { nome: "Londrina", uf: "PR" },
  { nome: "Wenceslau Braz", uf: "PR" },
  { nome: "Ponta Grossa", uf: "PR" },
] as const;

/** Chaves "UF|cidade normalizada" das cidades atendidas. */
const CIDADES_COBERTAS = new Set<string>([
  "PR|abatia",
  "PR|almirante tamandare",
  "PR|alto parana",
  "PR|alvorada do sul",
  "PR|andira",
  "PR|angulo",
  "PR|antonio olinto",
  "PR|apucarana",
  "PR|arapongas",
  "PR|arapoti",
  "PR|araucaria",
  "PR|assai",
  "PR|astorga",
  "PR|atalaia",
  "PR|balsa nova",
  "PR|bandeirantes",
  "PR|barbosa ferraz",
  "PR|barra do jacare",
  "PR|bela vista do paraiso",
  "PR|bocaiuva do sul",
  "PR|bom sucesso",
  "PR|borrazopolis",
  "PR|cafeara",
  "PR|california",
  "PR|cambara",
  "PR|cambe",
  "PR|cambira",
  "PR|campina grande do sul",
  "PR|campo do tenente",
  "PR|campo largo",
  "PR|campo magro",
  "PR|carambei",
  "PR|carlopolis",
  "PR|castro",
  "PR|centenario do sul",
  "PR|colombo",
  "PR|colorado",
  "PR|congonhinhas",
  "PR|conselheiro mairinck",
  "PR|contenda",
  "PR|cornelio procopio",
  "PR|cruzeiro do sul",
  "PR|cruzmaltina",
  "PR|curitiba",
  "PR|curiuva",
  "PR|doutor camargo",
  "PR|doutor ulysses",
  "PR|faxinal",
  "PR|fazenda rio grande",
  "PR|fenix",
  "PR|fernandes pinheiro",
  "PR|figueira",
  "PR|florai",
  "PR|floresta",
  "PR|florestopolis",
  "PR|florida",
  "PR|grandes rios",
  "PR|guamiranga",
  "PR|guapirama",
  "PR|guaraci",
  "PR|ibaiti",
  "PR|ibipora",
  "PR|iguaracu",
  "PR|imbau",
  "PR|imbituva",
  "PR|inacio martins",
  "PR|ipiranga",
  "PR|irati",
  "PR|itaguaje",
  "PR|itambaraca",
  "PR|itambe",
  "PR|itaperucu",
  "PR|ivai",
  "PR|ivaipora",
  "PR|ivatuba",
  "PR|jaboti",
  "PR|jacarezinho",
  "PR|jaguapita",
  "PR|jaguariaiva",
  "PR|jandaia do sul",
  "PR|japira",
  "PR|jardim alegre",
  "PR|jataizinho",
  "PR|joaquim tavora",
  "PR|jundiai do sul",
  "PR|kalore",
  "PR|lapa",
  "PR|leopolis",
  "PR|lidianopolis",
  "PR|lobato",
  "PR|londrina",
  "PR|lunardelli",
  "PR|lupionopolis",
  "PR|mallet",
  "PR|mandaguacu",
  "PR|mandaguari",
  "PR|mandirituba",
  "PR|marialva",
  "PR|marilandia do sul",
  "PR|maringa",
  "PR|marumbi",
  "PR|maua da serra",
  "PR|miraselva",
  "PR|munhoz de melo",
  "PR|nossa senhora das gracas",
  "PR|nova america da colina",
  "PR|nova esperanca",
  "PR|nova fatima",
  "PR|nova santa barbara",
  "PR|novo itacolomi",
  "PR|ortigueira",
  "PR|ourizona",
  "PR|paicandu",
  "PR|palmeira",
  "PR|paranacity",
  "PR|paranapoema",
  "PR|pinhais",
  "PR|pinhalao",
  "PR|pirai do sul",
  "PR|piraquara",
  "PR|pitangueiras",
  "PR|ponta grossa",
  "PR|porecatu",
  "PR|porto amazonas",
  "PR|prado ferreira",
  "PR|presidente castelo branco",
  "PR|primeiro de maio",
  "PR|prudentopolis",
  "PR|quatigua",
  "PR|quatro barras",
  "PR|quinta do sol",
  "PR|quitandinha",
  "PR|rancho alegre",
  "PR|reboucas",
  "PR|reserva",
  "PR|ribeirao claro",
  "PR|ribeirao do pinhal",
  "PR|rio azul",
  "PR|rio bom",
  "PR|rio branco do ivai",
  "PR|rio branco do sul",
  "PR|rio negro",
  "PR|rolandia",
  "PR|rosario do ivai",
  "PR|sabaudia",
  "PR|salto do itarare",
  "PR|santa amelia",
  "PR|santa cecilia do pavao",
  "PR|santa fe",
  "PR|santa ines",
  "PR|santa mariana",
  "PR|santana do itarare",
  "PR|santo antonio da platina",
  "PR|santo antonio do paraiso",
  "PR|santo inacio",
  "PR|sao jeronimo da serra",
  "PR|sao joao do ivai",
  "PR|sao joao do triunfo",
  "PR|sao jorge do ivai",
  "PR|sao jose da boa vista",
  "PR|sao jose dos pinhais",
  "PR|sao mateus do sul",
  "PR|sao pedro do ivai",
  "PR|sao sebastiao da amoreira",
  "PR|sapopema",
  "PR|sarandi",
  "PR|senges",
  "PR|sertaneja",
  "PR|sertanopolis",
  "PR|siqueira campos",
  "PR|tamarana",
  "PR|teixeira soares",
  "PR|telemaco borba",
  "PR|tibagi",
  "PR|tomazina",
  "PR|tunas do parana",
  "PR|uniflor",
  "PR|urai",
  "PR|ventania",
  "PR|wenceslau braz",
  "SP|anhumas",
  "SP|arandu",
  "SP|assis",
  "SP|barao de antonina",
  "SP|barra do chapeu",
  "SP|bernardino de campos",
  "SP|bom sucesso de itarare",
  "SP|candido mota",
  "SP|canitar",
  "SP|cerqueira cesar",
  "SP|chavantes",
  "SP|coronel macedo",
  "SP|cruzalia",
  "SP|estrela do norte",
  "SP|fartura",
  "SP|florinia",
  "SP|iepe",
  "SP|ipaussu",
  "SP|itabera",
  "SP|itai",
  "SP|itapeva",
  "SP|itapirapua paulista",
  "SP|itaporanga",
  "SP|itarare",
  "SP|manduri",
  "SP|maracai",
  "SP|nantes",
  "SP|narandiba",
  "SP|nova campina",
  "SP|oleo",
  "SP|ourinhos",
  "SP|palmital",
  "SP|paraguacu paulista",
  "SP|pedrinhas paulista",
  "SP|piraju",
  "SP|pirapozinho",
  "SP|ribeira",
  "SP|ribeirao branco",
  "SP|riversul",
  "SP|salto grande",
  "SP|sandovalina",
  "SP|santa cruz do rio pardo",
  "SP|sarutaia",
  "SP|taciba",
  "SP|taguai",
  "SP|taquarituba",
  "SP|taquarivai",
  "SP|tarabai",
  "SP|taruma",
  "SP|tejupa",
  "SP|timburi",
]);

export function normalizarCidade(nome: string): string {
  return nome
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");
}

/** true quando a cidade está dentro do raio de atendimento. */
export function cidadeNaCobertura(
  cidade: string | null | undefined,
  uf: string | null | undefined,
): boolean {
  if (!cidade || !uf) return false;
  return CIDADES_COBERTAS.has(`${uf.trim().toUpperCase()}|${normalizarCidade(cidade)}`);
}
