/**
 * Área de cobertura LZ7 — cidades a até 350 km, em linha reta, de uma das bases:
 * Londrina/PR, Wenceslau Braz/PR e Ponta Grossa/PR.
 *
 * Lista gerada a partir das coordenadas oficiais dos municípios (IBGE).
 * Não editar manualmente: regenerar se o raio ou as bases mudarem.
 */

export const RAIO_COBERTURA_KM = 350;

export const BASES_LZ7 = [
  { nome: "Londrina", uf: "PR" },
  { nome: "Wenceslau Braz", uf: "PR" },
  { nome: "Ponta Grossa", uf: "PR" },
] as const;

/** Chaves "UF|cidade normalizada" das cidades atendidas. */
const CIDADES_COBERTAS = new Set<string>([
  "PR|abatia",
  "PR|adrianopolis",
  "PR|agudos do sul",
  "PR|almirante tamandare",
  "PR|altamira do parana",
  "PR|alto paraiso",
  "PR|alto parana",
  "PR|alto piquiri",
  "PR|altonia",
  "PR|alvorada do sul",
  "PR|amapora",
  "PR|ampere",
  "PR|anahy",
  "PR|andira",
  "PR|angulo",
  "PR|antonina",
  "PR|antonio olinto",
  "PR|apucarana",
  "PR|arapongas",
  "PR|arapoti",
  "PR|arapua",
  "PR|araruna",
  "PR|araucaria",
  "PR|ariranha do ivai",
  "PR|assai",
  "PR|assis chateaubriand",
  "PR|astorga",
  "PR|atalaia",
  "PR|balsa nova",
  "PR|bandeirantes",
  "PR|barbosa ferraz",
  "PR|barra do jacare",
  "PR|bela vista do paraiso",
  "PR|bituruna",
  "PR|boa esperanca",
  "PR|boa esperanca do iguacu",
  "PR|boa ventura de sao roque",
  "PR|boa vista da aparecida",
  "PR|bocaiuva do sul",
  "PR|bom sucesso",
  "PR|bom sucesso do sul",
  "PR|borrazopolis",
  "PR|braganey",
  "PR|brasilandia do sul",
  "PR|cafeara",
  "PR|cafelandia",
  "PR|cafezal do sul",
  "PR|california",
  "PR|cambara",
  "PR|cambe",
  "PR|cambira",
  "PR|campina da lagoa",
  "PR|campina do simao",
  "PR|campina grande do sul",
  "PR|campo bonito",
  "PR|campo do tenente",
  "PR|campo largo",
  "PR|campo magro",
  "PR|campo mourao",
  "PR|candido de abreu",
  "PR|candoi",
  "PR|cantagalo",
  "PR|capitao leonidas marques",
  "PR|carambei",
  "PR|carlopolis",
  "PR|cascavel",
  "PR|castro",
  "PR|catanduvas",
  "PR|centenario do sul",
  "PR|cerro azul",
  "PR|ceu azul",
  "PR|chopinzinho",
  "PR|cianorte",
  "PR|cidade gaucha",
  "PR|clevelandia",
  "PR|colombo",
  "PR|colorado",
  "PR|congonhinhas",
  "PR|conselheiro mairinck",
  "PR|contenda",
  "PR|corbelia",
  "PR|cornelio procopio",
  "PR|coronel domingos soares",
  "PR|coronel vivida",
  "PR|corumbatai do sul",
  "PR|cruz machado",
  "PR|cruzeiro do iguacu",
  "PR|cruzeiro do oeste",
  "PR|cruzeiro do sul",
  "PR|cruzmaltina",
  "PR|curitiba",
  "PR|curiuva",
  "PR|diamante d'oeste",
  "PR|diamante do norte",
  "PR|diamante do sul",
  "PR|dois vizinhos",
  "PR|douradina",
  "PR|doutor camargo",
  "PR|doutor ulysses",
  "PR|eneas marques",
  "PR|engenheiro beltrao",
  "PR|entre rios do oeste",
  "PR|esperanca nova",
  "PR|espigao alto do iguacu",
  "PR|farol",
  "PR|faxinal",
  "PR|fazenda rio grande",
  "PR|fenix",
  "PR|fernandes pinheiro",
  "PR|figueira",
  "PR|flor da serra do sul",
  "PR|florai",
  "PR|floresta",
  "PR|florestopolis",
  "PR|florida",
  "PR|formosa do oeste",
  "PR|foz do jordao",
  "PR|francisco alves",
  "PR|francisco beltrao",
  "PR|general carneiro",
  "PR|godoy moreira",
  "PR|goioere",
  "PR|goioxim",
  "PR|grandes rios",
  "PR|guaira",
  "PR|guairaca",
  "PR|guamiranga",
  "PR|guapirama",
  "PR|guaporema",
  "PR|guaraci",
  "PR|guaraniacu",
  "PR|guarapuava",
  "PR|guaraquecaba",
  "PR|guaratuba",
  "PR|honorio serpa",
  "PR|ibaiti",
  "PR|ibema",
  "PR|ibipora",
  "PR|icaraima",
  "PR|iguaracu",
  "PR|iguatu",
  "PR|imbau",
  "PR|imbituva",
  "PR|inacio martins",
  "PR|inaja",
  "PR|indianopolis",
  "PR|ipiranga",
  "PR|ipora",
  "PR|iracema do oeste",
  "PR|irati",
  "PR|iretama",
  "PR|itaguaje",
  "PR|itambaraca",
  "PR|itambe",
  "PR|itapejara d'oeste",
  "PR|itaperucu",
  "PR|itauna do sul",
  "PR|ivai",
  "PR|ivaipora",
  "PR|ivate",
  "PR|ivatuba",
  "PR|jaboti",
  "PR|jacarezinho",
  "PR|jaguapita",
  "PR|jaguariaiva",
  "PR|jandaia do sul",
  "PR|janiopolis",
  "PR|japira",
  "PR|japura",
  "PR|jardim alegre",
  "PR|jardim olinda",
  "PR|jataizinho",
  "PR|jesuitas",
  "PR|joaquim tavora",
  "PR|jundiai do sul",
  "PR|juranda",
  "PR|jussara",
  "PR|kalore",
  "PR|lapa",
  "PR|laranjal",
  "PR|laranjeiras do sul",
  "PR|leopolis",
  "PR|lidianopolis",
  "PR|lindoeste",
  "PR|loanda",
  "PR|lobato",
  "PR|londrina",
  "PR|luiziana",
  "PR|lunardelli",
  "PR|lupionopolis",
  "PR|mallet",
  "PR|mambore",
  "PR|mandaguacu",
  "PR|mandaguari",
  "PR|mandirituba",
  "PR|manfrinopolis",
  "PR|mangueirinha",
  "PR|manoel ribas",
  "PR|marechal candido rondon",
  "PR|maria helena",
  "PR|marialva",
  "PR|marilandia do sul",
  "PR|marilena",
  "PR|mariluz",
  "PR|maringa",
  "PR|mariopolis",
  "PR|maripa",
  "PR|marmeleiro",
  "PR|marquinho",
  "PR|marumbi",
  "PR|matinhos",
  "PR|mato rico",
  "PR|maua da serra",
  "PR|mercedes",
  "PR|mirador",
  "PR|miraselva",
  "PR|moreira sales",
  "PR|morretes",
  "PR|munhoz de melo",
  "PR|nossa senhora das gracas",
  "PR|nova alianca do ivai",
  "PR|nova america da colina",
  "PR|nova aurora",
  "PR|nova cantu",
  "PR|nova esperanca",
  "PR|nova esperanca do sudoeste",
  "PR|nova fatima",
  "PR|nova laranjeiras",
  "PR|nova londrina",
  "PR|nova olimpia",
  "PR|nova prata do iguacu",
  "PR|nova santa barbara",
  "PR|nova santa rosa",
  "PR|nova tebas",
  "PR|novo itacolomi",
  "PR|ortigueira",
  "PR|ourizona",
  "PR|ouro verde do oeste",
  "PR|paicandu",
  "PR|palmas",
  "PR|palmeira",
  "PR|palmital",
  "PR|palotina",
  "PR|paraiso do norte",
  "PR|paranacity",
  "PR|paranagua",
  "PR|paranapoema",
  "PR|paranavai",
  "PR|pato bragado",
  "PR|pato branco",
  "PR|paula freitas",
  "PR|paulo frontin",
  "PR|peabiru",
  "PR|perobal",
  "PR|perola",
  "PR|pien",
  "PR|pinhais",
  "PR|pinhal de sao bento",
  "PR|pinhalao",
  "PR|pinhao",
  "PR|pirai do sul",
  "PR|piraquara",
  "PR|pitanga",
  "PR|pitangueiras",
  "PR|planaltina do parana",
  "PR|ponta grossa",
  "PR|pontal do parana",
  "PR|porecatu",
  "PR|porto amazonas",
  "PR|porto barreiro",
  "PR|porto rico",
  "PR|porto vitoria",
  "PR|prado ferreira",
  "PR|presidente castelo branco",
  "PR|primeiro de maio",
  "PR|prudentopolis",
  "PR|quarto centenario",
  "PR|quatigua",
  "PR|quatro barras",
  "PR|quatro pontes",
  "PR|quedas do iguacu",
  "PR|querencia do norte",
  "PR|quinta do sol",
  "PR|quitandinha",
  "PR|rancho alegre",
  "PR|rancho alegre d'oeste",
  "PR|realeza",
  "PR|reboucas",
  "PR|renascenca",
  "PR|reserva",
  "PR|reserva do iguacu",
  "PR|ribeirao claro",
  "PR|ribeirao do pinhal",
  "PR|rio azul",
  "PR|rio bom",
  "PR|rio bonito do iguacu",
  "PR|rio branco do ivai",
  "PR|rio branco do sul",
  "PR|rio negro",
  "PR|rolandia",
  "PR|roncador",
  "PR|rondon",
  "PR|rosario do ivai",
  "PR|sabaudia",
  "PR|salgado filho",
  "PR|salto do itarare",
  "PR|salto do lontra",
  "PR|santa amelia",
  "PR|santa cecilia do pavao",
  "PR|santa cruz de monte castelo",
  "PR|santa fe",
  "PR|santa ines",
  "PR|santa isabel do ivai",
  "PR|santa izabel do oeste",
  "PR|santa lucia",
  "PR|santa maria do oeste",
  "PR|santa mariana",
  "PR|santa monica",
  "PR|santa tereza do oeste",
  "PR|santana do itarare",
  "PR|santo antonio da platina",
  "PR|santo antonio do caiua",
  "PR|santo antonio do paraiso",
  "PR|santo inacio",
  "PR|sao carlos do ivai",
  "PR|sao jeronimo da serra",
  "PR|sao joao",
  "PR|sao joao do caiua",
  "PR|sao joao do ivai",
  "PR|sao joao do triunfo",
  "PR|sao jorge d'oeste",
  "PR|sao jorge do ivai",
  "PR|sao jorge do patrocinio",
  "PR|sao jose da boa vista",
  "PR|sao jose das palmeiras",
  "PR|sao jose dos pinhais",
  "PR|sao manoel do parana",
  "PR|sao mateus do sul",
  "PR|sao pedro do iguacu",
  "PR|sao pedro do ivai",
  "PR|sao pedro do parana",
  "PR|sao sebastiao da amoreira",
  "PR|sao tome",
  "PR|sapopema",
  "PR|sarandi",
  "PR|saudade do iguacu",
  "PR|senges",
  "PR|sertaneja",
  "PR|sertanopolis",
  "PR|siqueira campos",
  "PR|sulina",
  "PR|tamarana",
  "PR|tamboara",
  "PR|tapejara",
  "PR|tapira",
  "PR|teixeira soares",
  "PR|telemaco borba",
  "PR|terra boa",
  "PR|terra rica",
  "PR|terra roxa",
  "PR|tibagi",
  "PR|tijucas do sul",
  "PR|toledo",
  "PR|tomazina",
  "PR|tres barras do parana",
  "PR|tunas do parana",
  "PR|tuneiras do oeste",
  "PR|tupassi",
  "PR|turvo",
  "PR|ubirata",
  "PR|umuarama",
  "PR|uniao da vitoria",
  "PR|uniflor",
  "PR|urai",
  "PR|ventania",
  "PR|vera cruz do oeste",
  "PR|vere",
  "PR|virmond",
  "PR|vitorino",
  "PR|wenceslau braz",
  "PR|xambre",
  "SP|adamantina",
  "SP|adolfo",
  "SP|aguas de santa barbara",
  "SP|aguas de sao pedro",
  "SP|agudos",
  "SP|alambari",
  "SP|alfredo marcondes",
  "SP|alto alegre",
  "SP|aluminio",
  "SP|alvares machado",
  "SP|alvaro de carvalho",
  "SP|alvinlandia",
  "SP|americana",
  "SP|americo brasiliense",
  "SP|amparo",
  "SP|analandia",
  "SP|andradina",
  "SP|angatuba",
  "SP|anhembi",
  "SP|anhumas",
  "SP|aparecida d'oeste",
  "SP|apiai",
  "SP|aracariguama",
  "SP|aracatuba",
  "SP|aracoiaba da serra",
  "SP|arandu",
  "SP|araraquara",
  "SP|araras",
  "SP|arco-iris",
  "SP|arealva",
  "SP|areiopolis",
  "SP|ariranha",
  "SP|artur nogueira",
  "SP|assis",
  "SP|atibaia",
  "SP|auriflama",
  "SP|avai",
  "SP|avanhandava",
  "SP|avare",
  "SP|bady bassitt",
  "SP|balbinos",
  "SP|balsamo",
  "SP|barao de antonina",
  "SP|barbosa",
  "SP|bariri",
  "SP|barra bonita",
  "SP|barra do chapeu",
  "SP|barra do turvo",
  "SP|barrinha",
  "SP|barueri",
  "SP|bastos",
  "SP|bauru",
  "SP|bento de abreu",
  "SP|bernardino de campos",
  "SP|bilac",
  "SP|birigui",
  "SP|boa esperanca do sul",
  "SP|bocaina",
  "SP|bofete",
  "SP|boituva",
  "SP|bom jesus dos perdoes",
  "SP|bom sucesso de itarare",
  "SP|bora",
  "SP|boraceia",
  "SP|borborema",
  "SP|borebi",
  "SP|botucatu",
  "SP|braganca paulista",
  "SP|brauna",
  "SP|brejo alegre",
  "SP|brotas",
  "SP|buri",
  "SP|buritama",
  "SP|cabralia paulista",
  "SP|cabreuva",
  "SP|cafelandia",
  "SP|caiabu",
  "SP|caieiras",
  "SP|caiua",
  "SP|cajamar",
  "SP|cajati",
  "SP|cajobi",
  "SP|campina do monte alegre",
  "SP|campinas",
  "SP|campo limpo paulista",
  "SP|campos novos paulista",
  "SP|cananeia",
  "SP|candido mota",
  "SP|candido rodrigues",
  "SP|canitar",
  "SP|capao bonito",
  "SP|capela do alto",
  "SP|capivari",
  "SP|carapicuiba",
  "SP|castilho",
  "SP|catanduva",
  "SP|catigua",
  "SP|cedral",
  "SP|cerqueira cesar",
  "SP|cerquilho",
  "SP|cesario lange",
  "SP|charqueada",
  "SP|chavantes",
  "SP|clementina",
  "SP|conchal",
  "SP|conchas",
  "SP|cordeiropolis",
  "SP|coroados",
  "SP|coronel macedo",
  "SP|corumbatai",
  "SP|cosmopolis",
  "SP|cosmorama",
  "SP|cotia",
  "SP|cruzalia",
  "SP|cubatao",
  "SP|descalvado",
  "SP|diadema",
  "SP|dirce reis",
  "SP|dobrada",
  "SP|dois corregos",
  "SP|dourado",
  "SP|dracena",
  "SP|duartina",
  "SP|dumont",
  "SP|echapora",
  "SP|eldorado",
  "SP|elias fausto",
  "SP|elisiario",
  "SP|embauba",
  "SP|embu das artes",
  "SP|embu-guacu",
  "SP|emilianopolis",
  "SP|engenheiro coelho",
  "SP|espirito santo do turvo",
  "SP|estiva gerbi",
  "SP|estrela d'oeste",
  "SP|estrela do norte",
  "SP|euclides da cunha paulista",
  "SP|fartura",
  "SP|fernando prestes",
  "SP|fernandopolis",
  "SP|fernao",
  "SP|flora rica",
  "SP|floreal",
  "SP|florida paulista",
  "SP|florinia",
  "SP|francisco morato",
  "SP|franco da rocha",
  "SP|gabriel monteiro",
  "SP|galia",
  "SP|garca",
  "SP|gastao vidigal",
  "SP|gaviao peixoto",
  "SP|general salgado",
  "SP|getulina",
  "SP|glicerio",
  "SP|guaicara",
  "SP|guaimbe",
  "SP|guapiacu",
  "SP|guapiara",
  "SP|guaracai",
  "SP|guaranta",
  "SP|guararapes",
  "SP|guarei",
  "SP|guariba",
  "SP|guarulhos",
  "SP|guatapara",
  "SP|guzolandia",
  "SP|herculandia",
  "SP|holambra",
  "SP|hortolandia",
  "SP|iacanga",
  "SP|iacri",
  "SP|iaras",
  "SP|ibate",
  "SP|ibira",
  "SP|ibirarema",
  "SP|ibitinga",
  "SP|ibiuna",
  "SP|iepe",
  "SP|igaracu do tiete",
  "SP|iguape",
  "SP|ilha comprida",
  "SP|ilha solteira",
  "SP|indaiatuba",
  "SP|indiana",
  "SP|inubia paulista",
  "SP|ipaussu",
  "SP|ipero",
  "SP|ipeuna",
  "SP|ipigua",
  "SP|iporanga",
  "SP|iracemapolis",
  "SP|irapua",
  "SP|irapuru",
  "SP|itabera",
  "SP|itai",
  "SP|itajobi",
  "SP|itaju",
  "SP|itanhaem",
  "SP|itaoca",
  "SP|itapecerica da serra",
  "SP|itapetininga",
  "SP|itapeva",
  "SP|itapevi",
  "SP|itapira",
  "SP|itapirapua paulista",
  "SP|itapolis",
  "SP|itaporanga",
  "SP|itapui",
  "SP|itapura",
  "SP|itarare",
  "SP|itariri",
  "SP|itatiba",
  "SP|itatinga",
  "SP|itirapina",
  "SP|itu",
  "SP|itupeva",
  "SP|jaboticabal",
  "SP|jaci",
  "SP|jacupiranga",
  "SP|jaguariuna",
  "SP|jales",
  "SP|jandira",
  "SP|jarinu",
  "SP|jau",
  "SP|joao ramalho",
  "SP|jose bonifacio",
  "SP|julio mesquita",
  "SP|jumirim",
  "SP|jundiai",
  "SP|junqueiropolis",
  "SP|juquia",
  "SP|juquitiba",
  "SP|laranjal paulista",
  "SP|lavinia",
  "SP|leme",
  "SP|lencois paulista",
  "SP|limeira",
  "SP|lins",
  "SP|lourdes",
  "SP|louveira",
  "SP|lucelia",
  "SP|lucianopolis",
  "SP|luis antonio",
  "SP|luiziania",
  "SP|lupercio",
  "SP|lutecia",
  "SP|macatuba",
  "SP|macaubal",
  "SP|magda",
  "SP|mairinque",
  "SP|mairipora",
  "SP|manduri",
  "SP|maraba paulista",
  "SP|maracai",
  "SP|marapoama",
  "SP|mariapolis",
  "SP|marilia",
  "SP|marinopolis",
  "SP|martinopolis",
  "SP|matao",
  "SP|maua",
  "SP|mendonca",
  "SP|meridiano",
  "SP|mineiros do tiete",
  "SP|miracatu",
  "SP|mirandopolis",
  "SP|mirante do paranapanema",
  "SP|mirassol",
  "SP|mirassolandia",
  "SP|mogi guacu",
  "SP|mogi mirim",
  "SP|mombuca",
  "SP|moncoes",
  "SP|mongagua",
  "SP|monte alegre do sul",
  "SP|monte alto",
  "SP|monte aprazivel",
  "SP|monte castelo",
  "SP|monte mor",
  "SP|morungaba",
  "SP|motuca",
  "SP|murutinga do sul",
  "SP|nantes",
  "SP|narandiba",
  "SP|neves paulista",
  "SP|nhandeara",
  "SP|nipoa",
  "SP|nova alianca",
  "SP|nova campina",
  "SP|nova canaa paulista",
  "SP|nova castilho",
  "SP|nova europa",
  "SP|nova guataporanga",
  "SP|nova independencia",
  "SP|nova luzitania",
  "SP|nova odessa",
  "SP|novais",
  "SP|novo horizonte",
  "SP|ocaucu",
  "SP|oleo",
  "SP|oriente",
  "SP|osasco",
  "SP|oscar bressane",
  "SP|osvaldo cruz",
  "SP|ourinhos",
  "SP|ouro verde",
  "SP|pacaembu",
  "SP|palmares paulista",
  "SP|palmeira d'oeste",
  "SP|palmital",
  "SP|panorama",
  "SP|paraguacu paulista",
  "SP|paraiso",
  "SP|paranapanema",
  "SP|parapua",
  "SP|pardinho",
  "SP|pariquera-acu",
  "SP|pauliceia",
  "SP|paulinia",
  "SP|paulistania",
  "SP|pederneiras",
  "SP|pedreira",
  "SP|pedrinhas paulista",
  "SP|pedro de toledo",
  "SP|penapolis",
  "SP|pereira barreto",
  "SP|pereiras",
  "SP|peruibe",
  "SP|piacatu",
  "SP|piedade",
  "SP|pilar do sul",
  "SP|pindorama",
  "SP|pinhalzinho",
  "SP|piquerobi",
  "SP|piracicaba",
  "SP|piraju",
  "SP|pirajui",
  "SP|pirangi",
  "SP|pirapora do bom jesus",
  "SP|pirapozinho",
  "SP|pirassununga",
  "SP|piratininga",
  "SP|planalto",
  "SP|platina",
  "SP|poloni",
  "SP|pompeia",
  "SP|pongai",
  "SP|pontalinda",
  "SP|porangaba",
  "SP|porto feliz",
  "SP|porto ferreira",
  "SP|potirendaba",
  "SP|pracinha",
  "SP|pradopolis",
  "SP|praia grande",
  "SP|pratania",
  "SP|presidente alves",
  "SP|presidente bernardes",
  "SP|presidente epitacio",
  "SP|presidente prudente",
  "SP|presidente venceslau",
  "SP|promissao",
  "SP|quadra",
  "SP|quata",
  "SP|queiroz",
  "SP|quintana",
  "SP|rafard",
  "SP|rancharia",
  "SP|regente feijo",
  "SP|reginopolis",
  "SP|registro",
  "SP|ribeira",
  "SP|ribeirao bonito",
  "SP|ribeirao branco",
  "SP|ribeirao do sul",
  "SP|ribeirao dos indios",
  "SP|ribeirao grande",
  "SP|ribeirao pires",
  "SP|rincao",
  "SP|rinopolis",
  "SP|rio claro",
  "SP|rio das pedras",
  "SP|rio grande da serra",
  "SP|riversul",
  "SP|rosana",
  "SP|rubiacea",
  "SP|rubineia",
  "SP|sabino",
  "SP|sagres",
  "SP|sales",
  "SP|salmourao",
  "SP|saltinho",
  "SP|salto",
  "SP|salto de pirapora",
  "SP|salto grande",
  "SP|sandovalina",
  "SP|santa adelia",
  "SP|santa barbara d'oeste",
  "SP|santa cruz da conceicao",
  "SP|santa cruz das palmeiras",
  "SP|santa cruz do rio pardo",
  "SP|santa ernestina",
  "SP|santa fe do sul",
  "SP|santa gertrudes",
  "SP|santa lucia",
  "SP|santa maria da serra",
  "SP|santa mercedes",
  "SP|santa rita do passa quatro",
  "SP|santa salete",
  "SP|santana da ponte pensa",
  "SP|santana de parnaiba",
  "SP|santo anastacio",
  "SP|santo andre",
  "SP|santo antonio de posse",
  "SP|santo antonio do aracangua",
  "SP|santo expedito",
  "SP|santopolis do aguapei",
  "SP|sao bernardo do campo",
  "SP|sao caetano do sul",
  "SP|sao carlos",
  "SP|sao francisco",
  "SP|sao joao das duas pontes",
  "SP|sao joao de iracema",
  "SP|sao joao do pau d'alho",
  "SP|sao jose do rio preto",
  "SP|sao lourenco da serra",
  "SP|sao manuel",
  "SP|sao miguel arcanjo",
  "SP|sao paulo",
  "SP|sao pedro",
  "SP|sao pedro do turvo",
  "SP|sao roque",
  "SP|sao vicente",
  "SP|sarapui",
  "SP|sarutaia",
  "SP|sebastianopolis do sul",
  "SP|serra negra",
  "SP|sete barras",
  "SP|sorocaba",
  "SP|sud mennucci",
  "SP|sumare",
  "SP|suzanapolis",
  "SP|tabapua",
  "SP|tabatinga",
  "SP|taboao da serra",
  "SP|taciba",
  "SP|taguai",
  "SP|taiacu",
  "SP|taiuva",
  "SP|tanabi",
  "SP|tapirai",
  "SP|taquaral",
  "SP|taquaritinga",
  "SP|taquarituba",
  "SP|taquarivai",
  "SP|tarabai",
  "SP|taruma",
  "SP|tatui",
  "SP|tejupa",
  "SP|teodoro sampaio",
  "SP|tiete",
  "SP|timburi",
  "SP|torre de pedra",
  "SP|torrinha",
  "SP|trabiju",
  "SP|tres fronteiras",
  "SP|tuiuti",
  "SP|tupa",
  "SP|tupi paulista",
  "SP|turiuba",
  "SP|ubarana",
  "SP|ubirajara",
  "SP|uchoa",
  "SP|uniao paulista",
  "SP|urania",
  "SP|uru",
  "SP|urupes",
  "SP|valentim gentil",
  "SP|valinhos",
  "SP|valparaiso",
  "SP|vargem grande paulista",
  "SP|varzea paulista",
  "SP|vera cruz",
  "SP|vinhedo",
  "SP|vista alegre do alto",
  "SP|votorantim",
  "SP|votuporanga",
  "SP|zacarias",
]);

export function normalizarCidade(nome: string): string {
  return nome
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");
}

/** true quando a cidade está dentro do raio de atendimento. */
export function cidadeNaCobertura(
  cidade: string | null | undefined,
  uf: string | null | undefined,
): boolean {
  if (!cidade || !uf) return false;
  return CIDADES_COBERTAS.has(`${uf.trim().toUpperCase()}|${normalizarCidade(cidade)}`);
}
