/**
 * Área de cobertura LZ7 — cidades a até 120 km, em linha reta, de uma das bases:
 * Londrina/PR, Wenceslau Braz/PR e Ponta Grossa/PR.
 *
 * Lista gerada a partir das coordenadas oficiais dos municípios (IBGE), já com a base
 * mais próxima de cada cidade (usada na roleta de vendedores do quiz).
 * Não editar manualmente: regenerar se o raio ou as bases mudarem.
 */

export const RAIO_COBERTURA_KM = 120;

export const BASES_LZ7 = [
  { nome: "Londrina", uf: "PR" },
  { nome: "Wenceslau Braz", uf: "PR" },
  { nome: "Ponta Grossa", uf: "PR" },
] as const;

export type BaseLZ7 = "londrina" | "wenceslau_braz" | "ponta_grossa";

/** Chave "UF|cidade normalizada" → base mais próxima (menor distância em linha reta). */
const CIDADES_COBERTAS: Record<string, BaseLZ7> = {
  "PR|abatia": "wenceslau_braz",
  "PR|almirante tamandare": "ponta_grossa",
  "PR|alto parana": "londrina",
  "PR|alvorada do sul": "londrina",
  "PR|andira": "londrina",
  "PR|angulo": "londrina",
  "PR|antonio olinto": "ponta_grossa",
  "PR|apucarana": "londrina",
  "PR|arapongas": "londrina",
  "PR|arapoti": "wenceslau_braz",
  "PR|araucaria": "ponta_grossa",
  "PR|assai": "londrina",
  "PR|astorga": "londrina",
  "PR|atalaia": "londrina",
  "PR|balsa nova": "ponta_grossa",
  "PR|bandeirantes": "londrina",
  "PR|barbosa ferraz": "londrina",
  "PR|barra do jacare": "wenceslau_braz",
  "PR|bela vista do paraiso": "londrina",
  "PR|bocaiuva do sul": "ponta_grossa",
  "PR|bom sucesso": "londrina",
  "PR|borrazopolis": "londrina",
  "PR|cafeara": "londrina",
  "PR|california": "londrina",
  "PR|cambara": "wenceslau_braz",
  "PR|cambe": "londrina",
  "PR|cambira": "londrina",
  "PR|campina grande do sul": "ponta_grossa",
  "PR|campo do tenente": "ponta_grossa",
  "PR|campo largo": "ponta_grossa",
  "PR|campo magro": "ponta_grossa",
  "PR|carambei": "ponta_grossa",
  "PR|carlopolis": "wenceslau_braz",
  "PR|castro": "ponta_grossa",
  "PR|centenario do sul": "londrina",
  "PR|colombo": "ponta_grossa",
  "PR|colorado": "londrina",
  "PR|congonhinhas": "londrina",
  "PR|conselheiro mairinck": "wenceslau_braz",
  "PR|contenda": "ponta_grossa",
  "PR|cornelio procopio": "londrina",
  "PR|cruzeiro do sul": "londrina",
  "PR|cruzmaltina": "londrina",
  "PR|curitiba": "ponta_grossa",
  "PR|curiuva": "wenceslau_braz",
  "PR|doutor camargo": "londrina",
  "PR|doutor ulysses": "wenceslau_braz",
  "PR|faxinal": "londrina",
  "PR|fazenda rio grande": "ponta_grossa",
  "PR|fenix": "londrina",
  "PR|fernandes pinheiro": "ponta_grossa",
  "PR|figueira": "wenceslau_braz",
  "PR|florai": "londrina",
  "PR|floresta": "londrina",
  "PR|florestopolis": "londrina",
  "PR|florida": "londrina",
  "PR|grandes rios": "londrina",
  "PR|guamiranga": "ponta_grossa",
  "PR|guapirama": "wenceslau_braz",
  "PR|guaraci": "londrina",
  "PR|ibaiti": "wenceslau_braz",
  "PR|ibipora": "londrina",
  "PR|iguaracu": "londrina",
  "PR|imbau": "ponta_grossa",
  "PR|imbituva": "ponta_grossa",
  "PR|inacio martins": "ponta_grossa",
  "PR|ipiranga": "ponta_grossa",
  "PR|irati": "ponta_grossa",
  "PR|itaguaje": "londrina",
  "PR|itambaraca": "londrina",
  "PR|itambe": "londrina",
  "PR|itaperucu": "ponta_grossa",
  "PR|ivai": "ponta_grossa",
  "PR|ivaipora": "londrina",
  "PR|ivatuba": "londrina",
  "PR|jaboti": "wenceslau_braz",
  "PR|jacarezinho": "wenceslau_braz",
  "PR|jaguapita": "londrina",
  "PR|jaguariaiva": "wenceslau_braz",
  "PR|jandaia do sul": "londrina",
  "PR|japira": "wenceslau_braz",
  "PR|jardim alegre": "londrina",
  "PR|jataizinho": "londrina",
  "PR|joaquim tavora": "wenceslau_braz",
  "PR|jundiai do sul": "wenceslau_braz",
  "PR|kalore": "londrina",
  "PR|lapa": "ponta_grossa",
  "PR|leopolis": "londrina",
  "PR|lidianopolis": "londrina",
  "PR|lobato": "londrina",
  "PR|londrina": "londrina",
  "PR|lunardelli": "londrina",
  "PR|lupionopolis": "londrina",
  "PR|mallet": "ponta_grossa",
  "PR|mandaguacu": "londrina",
  "PR|mandaguari": "londrina",
  "PR|mandirituba": "ponta_grossa",
  "PR|marialva": "londrina",
  "PR|marilandia do sul": "londrina",
  "PR|maringa": "londrina",
  "PR|marumbi": "londrina",
  "PR|maua da serra": "londrina",
  "PR|miraselva": "londrina",
  "PR|munhoz de melo": "londrina",
  "PR|nossa senhora das gracas": "londrina",
  "PR|nova america da colina": "londrina",
  "PR|nova esperanca": "londrina",
  "PR|nova fatima": "londrina",
  "PR|nova santa barbara": "londrina",
  "PR|novo itacolomi": "londrina",
  "PR|ortigueira": "londrina",
  "PR|ourizona": "londrina",
  "PR|paicandu": "londrina",
  "PR|palmeira": "ponta_grossa",
  "PR|paranacity": "londrina",
  "PR|paranapoema": "londrina",
  "PR|pinhais": "ponta_grossa",
  "PR|pinhalao": "wenceslau_braz",
  "PR|pirai do sul": "ponta_grossa",
  "PR|piraquara": "ponta_grossa",
  "PR|pitangueiras": "londrina",
  "PR|ponta grossa": "ponta_grossa",
  "PR|porecatu": "londrina",
  "PR|porto amazonas": "ponta_grossa",
  "PR|prado ferreira": "londrina",
  "PR|presidente castelo branco": "londrina",
  "PR|primeiro de maio": "londrina",
  "PR|prudentopolis": "ponta_grossa",
  "PR|quatigua": "wenceslau_braz",
  "PR|quatro barras": "ponta_grossa",
  "PR|quinta do sol": "londrina",
  "PR|quitandinha": "ponta_grossa",
  "PR|rancho alegre": "londrina",
  "PR|reboucas": "ponta_grossa",
  "PR|reserva": "ponta_grossa",
  "PR|ribeirao claro": "wenceslau_braz",
  "PR|ribeirao do pinhal": "wenceslau_braz",
  "PR|rio azul": "ponta_grossa",
  "PR|rio bom": "londrina",
  "PR|rio branco do ivai": "londrina",
  "PR|rio branco do sul": "ponta_grossa",
  "PR|rio negro": "ponta_grossa",
  "PR|rolandia": "londrina",
  "PR|rosario do ivai": "londrina",
  "PR|sabaudia": "londrina",
  "PR|salto do itarare": "wenceslau_braz",
  "PR|santa amelia": "londrina",
  "PR|santa cecilia do pavao": "londrina",
  "PR|santa fe": "londrina",
  "PR|santa ines": "londrina",
  "PR|santa mariana": "londrina",
  "PR|santana do itarare": "wenceslau_braz",
  "PR|santo antonio da platina": "wenceslau_braz",
  "PR|santo antonio do paraiso": "londrina",
  "PR|santo inacio": "londrina",
  "PR|sao jeronimo da serra": "londrina",
  "PR|sao joao do ivai": "londrina",
  "PR|sao joao do triunfo": "ponta_grossa",
  "PR|sao jorge do ivai": "londrina",
  "PR|sao jose da boa vista": "wenceslau_braz",
  "PR|sao jose dos pinhais": "ponta_grossa",
  "PR|sao mateus do sul": "ponta_grossa",
  "PR|sao pedro do ivai": "londrina",
  "PR|sao sebastiao da amoreira": "londrina",
  "PR|sapopema": "wenceslau_braz",
  "PR|sarandi": "londrina",
  "PR|senges": "wenceslau_braz",
  "PR|sertaneja": "londrina",
  "PR|sertanopolis": "londrina",
  "PR|siqueira campos": "wenceslau_braz",
  "PR|tamarana": "londrina",
  "PR|teixeira soares": "ponta_grossa",
  "PR|telemaco borba": "wenceslau_braz",
  "PR|tibagi": "ponta_grossa",
  "PR|tomazina": "wenceslau_braz",
  "PR|tunas do parana": "ponta_grossa",
  "PR|uniflor": "londrina",
  "PR|urai": "londrina",
  "PR|ventania": "wenceslau_braz",
  "PR|wenceslau braz": "wenceslau_braz",
  "SP|anhumas": "londrina",
  "SP|arandu": "wenceslau_braz",
  "SP|assis": "londrina",
  "SP|barao de antonina": "wenceslau_braz",
  "SP|barra do chapeu": "wenceslau_braz",
  "SP|bernardino de campos": "wenceslau_braz",
  "SP|bom sucesso de itarare": "wenceslau_braz",
  "SP|candido mota": "londrina",
  "SP|canitar": "wenceslau_braz",
  "SP|cerqueira cesar": "wenceslau_braz",
  "SP|chavantes": "wenceslau_braz",
  "SP|coronel macedo": "wenceslau_braz",
  "SP|cruzalia": "londrina",
  "SP|estrela do norte": "londrina",
  "SP|fartura": "wenceslau_braz",
  "SP|florinia": "londrina",
  "SP|iepe": "londrina",
  "SP|ipaussu": "wenceslau_braz",
  "SP|itabera": "wenceslau_braz",
  "SP|itai": "wenceslau_braz",
  "SP|itapeva": "wenceslau_braz",
  "SP|itapirapua paulista": "wenceslau_braz",
  "SP|itaporanga": "wenceslau_braz",
  "SP|itarare": "wenceslau_braz",
  "SP|manduri": "wenceslau_braz",
  "SP|maracai": "londrina",
  "SP|nantes": "londrina",
  "SP|narandiba": "londrina",
  "SP|nova campina": "wenceslau_braz",
  "SP|oleo": "wenceslau_braz",
  "SP|ourinhos": "wenceslau_braz",
  "SP|palmital": "londrina",
  "SP|paraguacu paulista": "londrina",
  "SP|pedrinhas paulista": "londrina",
  "SP|piraju": "wenceslau_braz",
  "SP|pirapozinho": "londrina",
  "SP|ribeira": "wenceslau_braz",
  "SP|ribeirao branco": "wenceslau_braz",
  "SP|riversul": "wenceslau_braz",
  "SP|salto grande": "wenceslau_braz",
  "SP|sandovalina": "londrina",
  "SP|santa cruz do rio pardo": "wenceslau_braz",
  "SP|sarutaia": "wenceslau_braz",
  "SP|taciba": "londrina",
  "SP|taguai": "wenceslau_braz",
  "SP|taquarituba": "wenceslau_braz",
  "SP|taquarivai": "wenceslau_braz",
  "SP|tarabai": "londrina",
  "SP|taruma": "londrina",
  "SP|tejupa": "wenceslau_braz",
  "SP|timburi": "wenceslau_braz",
};

export function normalizarCidade(nome: string): string {
  return nome
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");
}

/** true quando a cidade está dentro do raio de atendimento. */
export function cidadeNaCobertura(
  cidade: string | null | undefined,
  uf: string | null | undefined,
): boolean {
  if (!cidade || !uf) return false;
  return baseMaisProxima(cidade, uf) !== null;
}

/** Base LZ7 mais próxima da cidade; null fora da cobertura ou cidade não reconhecida. */
export function baseMaisProxima(
  cidade: string | null | undefined,
  uf: string | null | undefined,
): BaseLZ7 | null {
  if (!cidade || !uf) return null;
  return CIDADES_COBERTAS[`${uf.trim().toUpperCase()}|${normalizarCidade(cidade)}`] ?? null;
}
