/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WppRouteImport } from './routes/wpp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprovarUsuarioRouteImport } from './routes/aprovar-usuario'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCoordenacaoRouteImport } from './routes/_authenticated/coordenacao'
import { Route as AuthenticatedBaixarAppRouteImport } from './routes/_authenticated/baixar-app'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicLizChatRouteImport } from './routes/api/public/liz-chat'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicPloomesWebhookRouteImport } from './routes/api/public/ploomes/webhook'
import { Route as ApiPublicHooksMetaSyncRouteImport } from './routes/api/public/hooks/meta-sync'

const WppRoute = WppRouteImport.update({
  id: '/wpp',
  path: '/wpp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarUsuarioRoute = AprovarUsuarioRouteImport.update({
  id: '/aprovar-usuario',
  path: '/aprovar-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordenacaoRoute =
  AuthenticatedCoordenacaoRouteImport.update({
    id: '/coordenacao',
    path: '/coordenacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaixarAppRoute = AuthenticatedBaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLizChatRoute = ApiPublicLizChatRouteImport.update({
  id: '/api/public/liz-chat',
  path: '/api/public/liz-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPloomesWebhookRoute = ApiPublicPloomesWebhookRouteImport.update({
  id: '/api/public/ploomes/webhook',
  path: '/api/public/ploomes/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaSyncRoute = ApiPublicHooksMetaSyncRouteImport.update({
  id: '/api/public/hooks/meta-sync',
  path: '/api/public/hooks/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/_authenticated/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/wpp'
    | '/admin'
    | '/app'
    | '/baixar-app'
    | '/coordenacao'
    | '/crm'
    | '/api/public/liz-chat'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/wpp'
    | '/admin'
    | '/app'
    | '/baixar-app'
    | '/coordenacao'
    | '/crm'
    | '/api/public/liz-chat'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/wpp'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/baixar-app'
    | '/_authenticated/coordenacao'
    | '/_authenticated/crm'
    | '/api/public/liz-chat'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprovarUsuarioRoute: typeof AprovarUsuarioRoute
  AuthRoute: typeof AuthRoute
  CapturaRoute: typeof CapturaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WppRoute: typeof WppRoute
  ApiPublicLizChatRoute: typeof ApiPublicLizChatRoute
  ApiPublicHooksMetaSyncRoute: typeof ApiPublicHooksMetaSyncRoute
  ApiPublicPloomesWebhookRoute: typeof ApiPublicPloomesWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpp': {
      id: '/wpp'
      path: '/wpp'
      fullPath: '/wpp'
      preLoaderRoute: typeof WppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar-usuario': {
      id: '/aprovar-usuario'
      path: '/aprovar-usuario'
      fullPath: '/aprovar-usuario'
      preLoaderRoute: typeof AprovarUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordenacao': {
      id: '/_authenticated/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof AuthenticatedCoordenacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baixar-app': {
      id: '/_authenticated/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof AuthenticatedBaixarAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/liz-chat': {
      id: '/api/public/liz-chat'
      path: '/api/public/liz-chat'
      fullPath: '/api/public/liz-chat'
      preLoaderRoute: typeof ApiPublicLizChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ploomes/webhook': {
      id: '/api/public/ploomes/webhook'
      path: '/api/public/ploomes/webhook'
      fullPath: '/api/public/ploomes/webhook'
      preLoaderRoute: typeof ApiPublicPloomesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-sync': {
      id: '/api/public/hooks/meta-sync'
      path: '/api/public/hooks/meta-sync'
      fullPath: '/api/public/hooks/meta-sync'
      preLoaderRoute: typeof ApiPublicHooksMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBaixarAppRoute: typeof AuthenticatedBaixarAppRoute
  AuthenticatedCoordenacaoRoute: typeof AuthenticatedCoordenacaoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBaixarAppRoute: AuthenticatedBaixarAppRoute,
  AuthenticatedCoordenacaoRoute: AuthenticatedCoordenacaoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprovarUsuarioRoute: AprovarUsuarioRoute,
  AuthRoute: AuthRoute,
  CapturaRoute: CapturaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WppRoute: WppRoute,
  ApiPublicLizChatRoute: ApiPublicLizChatRoute,
  ApiPublicHooksMetaSyncRoute: ApiPublicHooksMetaSyncRoute,
  ApiPublicPloomesWebhookRoute: ApiPublicPloomesWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
