/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WppRouteImport } from './routes/wpp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCoordenacaoRouteImport } from './routes/_authenticated/coordenacao'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPloomesWebhookRouteImport } from './routes/api/public/ploomes/webhook'
import { Route as ApiPublicHooksMetaSyncRouteImport } from './routes/api/public/hooks/meta-sync'

const WppRoute = WppRouteImport.update({
  id: '/wpp',
  path: '/wpp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordenacaoRoute =
  AuthenticatedCoordenacaoRouteImport.update({
    id: '/coordenacao',
    path: '/coordenacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPloomesWebhookRoute = ApiPublicPloomesWebhookRouteImport.update({
  id: '/api/public/ploomes/webhook',
  path: '/api/public/ploomes/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMetaSyncRoute = ApiPublicHooksMetaSyncRouteImport.update({
  id: '/api/public/hooks/meta-sync',
  path: '/api/public/hooks/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wpp': typeof WppRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/wpp'
    | '/admin'
    | '/coordenacao'
    | '/crm'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/wpp'
    | '/admin'
    | '/coordenacao'
    | '/crm'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/sitemap.xml'
    | '/wpp'
    | '/_authenticated/admin'
    | '/_authenticated/coordenacao'
    | '/_authenticated/crm'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WppRoute: typeof WppRoute
  ApiPublicHooksMetaSyncRoute: typeof ApiPublicHooksMetaSyncRoute
  ApiPublicPloomesWebhookRoute: typeof ApiPublicPloomesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpp': {
      id: '/wpp'
      path: '/wpp'
      fullPath: '/wpp'
      preLoaderRoute: typeof WppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordenacao': {
      id: '/_authenticated/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof AuthenticatedCoordenacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ploomes/webhook': {
      id: '/api/public/ploomes/webhook'
      path: '/api/public/ploomes/webhook'
      fullPath: '/api/public/ploomes/webhook'
      preLoaderRoute: typeof ApiPublicPloomesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-sync': {
      id: '/api/public/hooks/meta-sync'
      path: '/api/public/hooks/meta-sync'
      fullPath: '/api/public/hooks/meta-sync'
      preLoaderRoute: typeof ApiPublicHooksMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCoordenacaoRoute: typeof AuthenticatedCoordenacaoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCoordenacaoRoute: AuthenticatedCoordenacaoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WppRoute: WppRoute,
  ApiPublicHooksMetaSyncRoute: ApiPublicHooksMetaSyncRoute,
  ApiPublicPloomesWebhookRoute: ApiPublicPloomesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
