/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WppRouteImport } from './routes/wpp'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprovarUsuarioRouteImport } from './routes/aprovar-usuario'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedSdrLeadqualifiedRouteImport } from './routes/_authenticated/sdr-leadqualified'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedMarketingHubRouteImport } from './routes/_authenticated/marketing-hub'
import { Route as AuthenticatedLizStudioRouteImport } from './routes/_authenticated/liz-studio'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCoordenacaoRouteImport } from './routes/_authenticated/coordenacao'
import { Route as AuthenticatedBaixarAppRouteImport } from './routes/_authenticated/baixar-app'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedModIndexRouteImport } from './routes/_authenticated/mod/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTestApprovalEmailRouteImport } from './routes/api/public/test-approval-email'
import { Route as ApiPublicNotifyApprovalRouteImport } from './routes/api/public/notify-approval'
import { Route as ApiPublicMetaRunInsightsRouteImport } from './routes/api/public/meta-run-insights'
import { Route as ApiPublicLizImageRouteImport } from './routes/api/public/liz-image'
import { Route as ApiPublicLizChatRouteImport } from './routes/api/public/liz-chat'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicEnsureApprovedLoginRouteImport } from './routes/api/public/ensure-approved-login'
import { Route as AuthenticatedModSaudeRouteImport } from './routes/_authenticated/mod/saude'
import { Route as AuthenticatedModResponsaveisRouteImport } from './routes/_authenticated/mod/responsaveis'
import { Route as AuthenticatedModPloomesIntegracaoRouteImport } from './routes/_authenticated/mod/ploomes-integracao'
import { Route as AuthenticatedModMetaDebugRouteImport } from './routes/_authenticated/mod/meta-debug'
import { Route as AuthenticatedModMetaConversionsRouteImport } from './routes/_authenticated/mod/meta-conversions'
import { Route as AuthenticatedModMarketingRouteImport } from './routes/_authenticated/mod/marketing'
import { Route as AuthenticatedModIaRouteImport } from './routes/_authenticated/mod/ia'
import { Route as AuthenticatedModFinanceiroRouteImport } from './routes/_authenticated/mod/financeiro'
import { Route as AuthenticatedModDesignSystemRouteImport } from './routes/_authenticated/mod/design-system'
import { Route as AuthenticatedModChamadosRouteImport } from './routes/_authenticated/mod/chamados'
import { Route as AuthenticatedModBiRouteImport } from './routes/_authenticated/mod/bi'
import { Route as AuthenticatedModAutomacoesRouteImport } from './routes/_authenticated/mod/automacoes'
import { Route as AuthenticatedModAuditoriaRouteImport } from './routes/_authenticated/mod/auditoria'
import { Route as AuthenticatedModAdminRouteImport } from './routes/_authenticated/mod/admin'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedModWhatsappIndexRouteImport } from './routes/_authenticated/mod/whatsapp/index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicPloomesWebhookRouteImport } from './routes/api/public/ploomes/webhook'
import { Route as ApiPublicPloomesSyncUsersRouteImport } from './routes/api/public/ploomes/sync-users'
import { Route as ApiPublicHooksMetaSyncRouteImport } from './routes/api/public/hooks/meta-sync'
import { Route as AuthenticatedModWhatsappConhecimentoRouteImport } from './routes/_authenticated/mod/whatsapp/conhecimento'
import { Route as AuthenticatedModWhatsappConfigRouteImport } from './routes/_authenticated/mod/whatsapp/config'
import { Route as ApiPublicWaQueueProcessRouteImport } from './routes/api/public/wa/queue/process'
import { Route as ApiPublicMetaAudienceSyncRouteImport } from './routes/api/public/meta/audience/sync'
import { Route as ApiPublicMetaAudienceQualifiedDotcsvRouteImport } from './routes/api/public/meta/audience/qualified[.]csv'
import { Route as ApiPublicMetaAudienceCustomersDotcsvRouteImport } from './routes/api/public/meta/audience/customers[.]csv'

const WppRoute = WppRouteImport.update({
  id: '/wpp',
  path: '/wpp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarUsuarioRoute = AprovarUsuarioRouteImport.update({
  id: '/aprovar-usuario',
  path: '/aprovar-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSdrLeadqualifiedRoute =
  AuthenticatedSdrLeadqualifiedRouteImport.update({
    id: '/sdr-leadqualified',
    path: '/sdr-leadqualified',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingHubRoute =
  AuthenticatedMarketingHubRouteImport.update({
    id: '/marketing-hub',
    path: '/marketing-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLizStudioRoute = AuthenticatedLizStudioRouteImport.update({
  id: '/liz-studio',
  path: '/liz-studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordenacaoRoute =
  AuthenticatedCoordenacaoRouteImport.update({
    id: '/coordenacao',
    path: '/coordenacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaixarAppRoute = AuthenticatedBaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedModIndexRoute = AuthenticatedModIndexRouteImport.update({
  id: '/mod/',
  path: '/mod/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestApprovalEmailRoute =
  ApiPublicTestApprovalEmailRouteImport.update({
    id: '/api/public/test-approval-email',
    path: '/api/public/test-approval-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyApprovalRoute = ApiPublicNotifyApprovalRouteImport.update({
  id: '/api/public/notify-approval',
  path: '/api/public/notify-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaRunInsightsRoute =
  ApiPublicMetaRunInsightsRouteImport.update({
    id: '/api/public/meta-run-insights',
    path: '/api/public/meta-run-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLizImageRoute = ApiPublicLizImageRouteImport.update({
  id: '/api/public/liz-image',
  path: '/api/public/liz-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLizChatRoute = ApiPublicLizChatRouteImport.update({
  id: '/api/public/liz-chat',
  path: '/api/public/liz-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnsureApprovedLoginRoute =
  ApiPublicEnsureApprovedLoginRouteImport.update({
    id: '/api/public/ensure-approved-login',
    path: '/api/public/ensure-approved-login',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedModSaudeRoute = AuthenticatedModSaudeRouteImport.update({
  id: '/mod/saude',
  path: '/mod/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModResponsaveisRoute =
  AuthenticatedModResponsaveisRouteImport.update({
    id: '/mod/responsaveis',
    path: '/mod/responsaveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModPloomesIntegracaoRoute =
  AuthenticatedModPloomesIntegracaoRouteImport.update({
    id: '/mod/ploomes-integracao',
    path: '/mod/ploomes-integracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModMetaDebugRoute =
  AuthenticatedModMetaDebugRouteImport.update({
    id: '/mod/meta-debug',
    path: '/mod/meta-debug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModMetaConversionsRoute =
  AuthenticatedModMetaConversionsRouteImport.update({
    id: '/mod/meta-conversions',
    path: '/mod/meta-conversions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModMarketingRoute =
  AuthenticatedModMarketingRouteImport.update({
    id: '/mod/marketing',
    path: '/mod/marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModIaRoute = AuthenticatedModIaRouteImport.update({
  id: '/mod/ia',
  path: '/mod/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModFinanceiroRoute =
  AuthenticatedModFinanceiroRouteImport.update({
    id: '/mod/financeiro',
    path: '/mod/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModDesignSystemRoute =
  AuthenticatedModDesignSystemRouteImport.update({
    id: '/mod/design-system',
    path: '/mod/design-system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModChamadosRoute =
  AuthenticatedModChamadosRouteImport.update({
    id: '/mod/chamados',
    path: '/mod/chamados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModBiRoute = AuthenticatedModBiRouteImport.update({
  id: '/mod/bi',
  path: '/mod/bi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModAutomacoesRoute =
  AuthenticatedModAutomacoesRouteImport.update({
    id: '/mod/automacoes',
    path: '/mod/automacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModAuditoriaRoute =
  AuthenticatedModAuditoriaRouteImport.update({
    id: '/mod/auditoria',
    path: '/mod/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModAdminRoute = AuthenticatedModAdminRouteImport.update({
  id: '/mod/admin',
  path: '/mod/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModWhatsappIndexRoute =
  AuthenticatedModWhatsappIndexRouteImport.update({
    id: '/mod/whatsapp/',
    path: '/mod/whatsapp/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPloomesWebhookRoute = ApiPublicPloomesWebhookRouteImport.update({
  id: '/api/public/ploomes/webhook',
  path: '/api/public/ploomes/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPloomesSyncUsersRoute =
  ApiPublicPloomesSyncUsersRouteImport.update({
    id: '/api/public/ploomes/sync-users',
    path: '/api/public/ploomes/sync-users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaSyncRoute = ApiPublicHooksMetaSyncRouteImport.update({
  id: '/api/public/hooks/meta-sync',
  path: '/api/public/hooks/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModWhatsappConhecimentoRoute =
  AuthenticatedModWhatsappConhecimentoRouteImport.update({
    id: '/mod/whatsapp/conhecimento',
    path: '/mod/whatsapp/conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModWhatsappConfigRoute =
  AuthenticatedModWhatsappConfigRouteImport.update({
    id: '/mod/whatsapp/config',
    path: '/mod/whatsapp/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWaQueueProcessRoute = ApiPublicWaQueueProcessRouteImport.update({
  id: '/api/public/wa/queue/process',
  path: '/api/public/wa/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaAudienceSyncRoute =
  ApiPublicMetaAudienceSyncRouteImport.update({
    id: '/api/public/meta/audience/sync',
    path: '/api/public/meta/audience/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaAudienceQualifiedDotcsvRoute =
  ApiPublicMetaAudienceQualifiedDotcsvRouteImport.update({
    id: '/api/public/meta/audience/qualified.csv',
    path: '/api/public/meta/audience/qualified.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaAudienceCustomersDotcsvRoute =
  ApiPublicMetaAudienceCustomersDotcsvRouteImport.update({
    id: '/api/public/meta/audience/customers.csv',
    path: '/api/public/meta/audience/customers.csv',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wpp': typeof WppRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/liz-studio': typeof AuthenticatedLizStudioRoute
  '/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/sdr-leadqualified': typeof AuthenticatedSdrLeadqualifiedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/mod/admin': typeof AuthenticatedModAdminRoute
  '/mod/auditoria': typeof AuthenticatedModAuditoriaRoute
  '/mod/automacoes': typeof AuthenticatedModAutomacoesRoute
  '/mod/bi': typeof AuthenticatedModBiRoute
  '/mod/chamados': typeof AuthenticatedModChamadosRoute
  '/mod/design-system': typeof AuthenticatedModDesignSystemRoute
  '/mod/financeiro': typeof AuthenticatedModFinanceiroRoute
  '/mod/ia': typeof AuthenticatedModIaRoute
  '/mod/marketing': typeof AuthenticatedModMarketingRoute
  '/mod/meta-conversions': typeof AuthenticatedModMetaConversionsRoute
  '/mod/meta-debug': typeof AuthenticatedModMetaDebugRoute
  '/mod/ploomes-integracao': typeof AuthenticatedModPloomesIntegracaoRoute
  '/mod/responsaveis': typeof AuthenticatedModResponsaveisRoute
  '/mod/saude': typeof AuthenticatedModSaudeRoute
  '/api/public/ensure-approved-login': typeof ApiPublicEnsureApprovedLoginRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/liz-image': typeof ApiPublicLizImageRoute
  '/api/public/meta-run-insights': typeof ApiPublicMetaRunInsightsRoute
  '/api/public/notify-approval': typeof ApiPublicNotifyApprovalRoute
  '/api/public/test-approval-email': typeof ApiPublicTestApprovalEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/mod/': typeof AuthenticatedModIndexRoute
  '/mod/whatsapp/config': typeof AuthenticatedModWhatsappConfigRoute
  '/mod/whatsapp/conhecimento': typeof AuthenticatedModWhatsappConhecimentoRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/sync-users': typeof ApiPublicPloomesSyncUsersRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/mod/whatsapp/': typeof AuthenticatedModWhatsappIndexRoute
  '/api/public/meta/audience/customers.csv': typeof ApiPublicMetaAudienceCustomersDotcsvRoute
  '/api/public/meta/audience/qualified.csv': typeof ApiPublicMetaAudienceQualifiedDotcsvRoute
  '/api/public/meta/audience/sync': typeof ApiPublicMetaAudienceSyncRoute
  '/api/public/wa/queue/process': typeof ApiPublicWaQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wpp': typeof WppRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/app': typeof AuthenticatedAppRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/liz-studio': typeof AuthenticatedLizStudioRoute
  '/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/sdr-leadqualified': typeof AuthenticatedSdrLeadqualifiedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/mod/admin': typeof AuthenticatedModAdminRoute
  '/mod/auditoria': typeof AuthenticatedModAuditoriaRoute
  '/mod/automacoes': typeof AuthenticatedModAutomacoesRoute
  '/mod/bi': typeof AuthenticatedModBiRoute
  '/mod/chamados': typeof AuthenticatedModChamadosRoute
  '/mod/design-system': typeof AuthenticatedModDesignSystemRoute
  '/mod/financeiro': typeof AuthenticatedModFinanceiroRoute
  '/mod/ia': typeof AuthenticatedModIaRoute
  '/mod/marketing': typeof AuthenticatedModMarketingRoute
  '/mod/meta-conversions': typeof AuthenticatedModMetaConversionsRoute
  '/mod/meta-debug': typeof AuthenticatedModMetaDebugRoute
  '/mod/ploomes-integracao': typeof AuthenticatedModPloomesIntegracaoRoute
  '/mod/responsaveis': typeof AuthenticatedModResponsaveisRoute
  '/mod/saude': typeof AuthenticatedModSaudeRoute
  '/api/public/ensure-approved-login': typeof ApiPublicEnsureApprovedLoginRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/liz-image': typeof ApiPublicLizImageRoute
  '/api/public/meta-run-insights': typeof ApiPublicMetaRunInsightsRoute
  '/api/public/notify-approval': typeof ApiPublicNotifyApprovalRoute
  '/api/public/test-approval-email': typeof ApiPublicTestApprovalEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/mod': typeof AuthenticatedModIndexRoute
  '/mod/whatsapp/config': typeof AuthenticatedModWhatsappConfigRoute
  '/mod/whatsapp/conhecimento': typeof AuthenticatedModWhatsappConhecimentoRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/sync-users': typeof ApiPublicPloomesSyncUsersRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/mod/whatsapp': typeof AuthenticatedModWhatsappIndexRoute
  '/api/public/meta/audience/customers.csv': typeof ApiPublicMetaAudienceCustomersDotcsvRoute
  '/api/public/meta/audience/qualified.csv': typeof ApiPublicMetaAudienceQualifiedDotcsvRoute
  '/api/public/meta/audience/sync': typeof ApiPublicMetaAudienceSyncRoute
  '/api/public/wa/queue/process': typeof ApiPublicWaQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprovar-usuario': typeof AprovarUsuarioRoute
  '/auth': typeof AuthRoute
  '/captura': typeof CapturaRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wpp': typeof WppRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/_authenticated/coordenacao': typeof AuthenticatedCoordenacaoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/liz-studio': typeof AuthenticatedLizStudioRoute
  '/_authenticated/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/sdr-leadqualified': typeof AuthenticatedSdrLeadqualifiedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/mod/admin': typeof AuthenticatedModAdminRoute
  '/_authenticated/mod/auditoria': typeof AuthenticatedModAuditoriaRoute
  '/_authenticated/mod/automacoes': typeof AuthenticatedModAutomacoesRoute
  '/_authenticated/mod/bi': typeof AuthenticatedModBiRoute
  '/_authenticated/mod/chamados': typeof AuthenticatedModChamadosRoute
  '/_authenticated/mod/design-system': typeof AuthenticatedModDesignSystemRoute
  '/_authenticated/mod/financeiro': typeof AuthenticatedModFinanceiroRoute
  '/_authenticated/mod/ia': typeof AuthenticatedModIaRoute
  '/_authenticated/mod/marketing': typeof AuthenticatedModMarketingRoute
  '/_authenticated/mod/meta-conversions': typeof AuthenticatedModMetaConversionsRoute
  '/_authenticated/mod/meta-debug': typeof AuthenticatedModMetaDebugRoute
  '/_authenticated/mod/ploomes-integracao': typeof AuthenticatedModPloomesIntegracaoRoute
  '/_authenticated/mod/responsaveis': typeof AuthenticatedModResponsaveisRoute
  '/_authenticated/mod/saude': typeof AuthenticatedModSaudeRoute
  '/api/public/ensure-approved-login': typeof ApiPublicEnsureApprovedLoginRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/liz-chat': typeof ApiPublicLizChatRoute
  '/api/public/liz-image': typeof ApiPublicLizImageRoute
  '/api/public/meta-run-insights': typeof ApiPublicMetaRunInsightsRoute
  '/api/public/notify-approval': typeof ApiPublicNotifyApprovalRoute
  '/api/public/test-approval-email': typeof ApiPublicTestApprovalEmailRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/mod/': typeof AuthenticatedModIndexRoute
  '/_authenticated/mod/whatsapp/config': typeof AuthenticatedModWhatsappConfigRoute
  '/_authenticated/mod/whatsapp/conhecimento': typeof AuthenticatedModWhatsappConhecimentoRoute
  '/api/public/hooks/meta-sync': typeof ApiPublicHooksMetaSyncRoute
  '/api/public/ploomes/sync-users': typeof ApiPublicPloomesSyncUsersRoute
  '/api/public/ploomes/webhook': typeof ApiPublicPloomesWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/mod/whatsapp/': typeof AuthenticatedModWhatsappIndexRoute
  '/api/public/meta/audience/customers.csv': typeof ApiPublicMetaAudienceCustomersDotcsvRoute
  '/api/public/meta/audience/qualified.csv': typeof ApiPublicMetaAudienceQualifiedDotcsvRoute
  '/api/public/meta/audience/sync': typeof ApiPublicMetaAudienceSyncRoute
  '/api/public/wa/queue/process': typeof ApiPublicWaQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/mcp'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/wpp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/agenda'
    | '/app'
    | '/baixar-app'
    | '/coordenacao'
    | '/crm'
    | '/hoje'
    | '/inventario'
    | '/leads'
    | '/liz-studio'
    | '/marketing-hub'
    | '/ranking'
    | '/sdr-leadqualified'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/mod/admin'
    | '/mod/auditoria'
    | '/mod/automacoes'
    | '/mod/bi'
    | '/mod/chamados'
    | '/mod/design-system'
    | '/mod/financeiro'
    | '/mod/ia'
    | '/mod/marketing'
    | '/mod/meta-conversions'
    | '/mod/meta-debug'
    | '/mod/ploomes-integracao'
    | '/mod/responsaveis'
    | '/mod/saude'
    | '/api/public/ensure-approved-login'
    | '/api/public/lead'
    | '/api/public/liz-chat'
    | '/api/public/liz-image'
    | '/api/public/meta-run-insights'
    | '/api/public/notify-approval'
    | '/api/public/test-approval-email'
    | '/lovable/email/suppression'
    | '/mod/'
    | '/mod/whatsapp/config'
    | '/mod/whatsapp/conhecimento'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/sync-users'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/mod/whatsapp/'
    | '/api/public/meta/audience/customers.csv'
    | '/api/public/meta/audience/qualified.csv'
    | '/api/public/meta/audience/sync'
    | '/api/public/wa/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/mcp'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/wpp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/agenda'
    | '/app'
    | '/baixar-app'
    | '/coordenacao'
    | '/crm'
    | '/hoje'
    | '/inventario'
    | '/leads'
    | '/liz-studio'
    | '/marketing-hub'
    | '/ranking'
    | '/sdr-leadqualified'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/mod/admin'
    | '/mod/auditoria'
    | '/mod/automacoes'
    | '/mod/bi'
    | '/mod/chamados'
    | '/mod/design-system'
    | '/mod/financeiro'
    | '/mod/ia'
    | '/mod/marketing'
    | '/mod/meta-conversions'
    | '/mod/meta-debug'
    | '/mod/ploomes-integracao'
    | '/mod/responsaveis'
    | '/mod/saude'
    | '/api/public/ensure-approved-login'
    | '/api/public/lead'
    | '/api/public/liz-chat'
    | '/api/public/liz-image'
    | '/api/public/meta-run-insights'
    | '/api/public/notify-approval'
    | '/api/public/test-approval-email'
    | '/lovable/email/suppression'
    | '/mod'
    | '/mod/whatsapp/config'
    | '/mod/whatsapp/conhecimento'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/sync-users'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/mod/whatsapp'
    | '/api/public/meta/audience/customers.csv'
    | '/api/public/meta/audience/qualified.csv'
    | '/api/public/meta/audience/sync'
    | '/api/public/wa/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprovar-usuario'
    | '/auth'
    | '/captura'
    | '/mcp'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/wpp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/app'
    | '/_authenticated/baixar-app'
    | '/_authenticated/coordenacao'
    | '/_authenticated/crm'
    | '/_authenticated/hoje'
    | '/_authenticated/inventario'
    | '/_authenticated/leads'
    | '/_authenticated/liz-studio'
    | '/_authenticated/marketing-hub'
    | '/_authenticated/ranking'
    | '/_authenticated/sdr-leadqualified'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/mod/admin'
    | '/_authenticated/mod/auditoria'
    | '/_authenticated/mod/automacoes'
    | '/_authenticated/mod/bi'
    | '/_authenticated/mod/chamados'
    | '/_authenticated/mod/design-system'
    | '/_authenticated/mod/financeiro'
    | '/_authenticated/mod/ia'
    | '/_authenticated/mod/marketing'
    | '/_authenticated/mod/meta-conversions'
    | '/_authenticated/mod/meta-debug'
    | '/_authenticated/mod/ploomes-integracao'
    | '/_authenticated/mod/responsaveis'
    | '/_authenticated/mod/saude'
    | '/api/public/ensure-approved-login'
    | '/api/public/lead'
    | '/api/public/liz-chat'
    | '/api/public/liz-image'
    | '/api/public/meta-run-insights'
    | '/api/public/notify-approval'
    | '/api/public/test-approval-email'
    | '/lovable/email/suppression'
    | '/_authenticated/mod/'
    | '/_authenticated/mod/whatsapp/config'
    | '/_authenticated/mod/whatsapp/conhecimento'
    | '/api/public/hooks/meta-sync'
    | '/api/public/ploomes/sync-users'
    | '/api/public/ploomes/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/mod/whatsapp/'
    | '/api/public/meta/audience/customers.csv'
    | '/api/public/meta/audience/qualified.csv'
    | '/api/public/meta/audience/sync'
    | '/api/public/wa/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprovarUsuarioRoute: typeof AprovarUsuarioRoute
  AuthRoute: typeof AuthRoute
  CapturaRoute: typeof CapturaRoute
  McpRoute: typeof McpRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WppRoute: typeof WppRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEnsureApprovedLoginRoute: typeof ApiPublicEnsureApprovedLoginRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicLizChatRoute: typeof ApiPublicLizChatRoute
  ApiPublicLizImageRoute: typeof ApiPublicLizImageRoute
  ApiPublicMetaRunInsightsRoute: typeof ApiPublicMetaRunInsightsRoute
  ApiPublicNotifyApprovalRoute: typeof ApiPublicNotifyApprovalRoute
  ApiPublicTestApprovalEmailRoute: typeof ApiPublicTestApprovalEmailRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksMetaSyncRoute: typeof ApiPublicHooksMetaSyncRoute
  ApiPublicPloomesSyncUsersRoute: typeof ApiPublicPloomesSyncUsersRoute
  ApiPublicPloomesWebhookRoute: typeof ApiPublicPloomesWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicMetaAudienceCustomersDotcsvRoute: typeof ApiPublicMetaAudienceCustomersDotcsvRoute
  ApiPublicMetaAudienceQualifiedDotcsvRoute: typeof ApiPublicMetaAudienceQualifiedDotcsvRoute
  ApiPublicMetaAudienceSyncRoute: typeof ApiPublicMetaAudienceSyncRoute
  ApiPublicWaQueueProcessRoute: typeof ApiPublicWaQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpp': {
      id: '/wpp'
      path: '/wpp'
      fullPath: '/wpp'
      preLoaderRoute: typeof WppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar-usuario': {
      id: '/aprovar-usuario'
      path: '/aprovar-usuario'
      fullPath: '/aprovar-usuario'
      preLoaderRoute: typeof AprovarUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sdr-leadqualified': {
      id: '/_authenticated/sdr-leadqualified'
      path: '/sdr-leadqualified'
      fullPath: '/sdr-leadqualified'
      preLoaderRoute: typeof AuthenticatedSdrLeadqualifiedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-hub': {
      id: '/_authenticated/marketing-hub'
      path: '/marketing-hub'
      fullPath: '/marketing-hub'
      preLoaderRoute: typeof AuthenticatedMarketingHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liz-studio': {
      id: '/_authenticated/liz-studio'
      path: '/liz-studio'
      fullPath: '/liz-studio'
      preLoaderRoute: typeof AuthenticatedLizStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordenacao': {
      id: '/_authenticated/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof AuthenticatedCoordenacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baixar-app': {
      id: '/_authenticated/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof AuthenticatedBaixarAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mod/': {
      id: '/_authenticated/mod/'
      path: '/mod'
      fullPath: '/mod/'
      preLoaderRoute: typeof AuthenticatedModIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-approval-email': {
      id: '/api/public/test-approval-email'
      path: '/api/public/test-approval-email'
      fullPath: '/api/public/test-approval-email'
      preLoaderRoute: typeof ApiPublicTestApprovalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-approval': {
      id: '/api/public/notify-approval'
      path: '/api/public/notify-approval'
      fullPath: '/api/public/notify-approval'
      preLoaderRoute: typeof ApiPublicNotifyApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-run-insights': {
      id: '/api/public/meta-run-insights'
      path: '/api/public/meta-run-insights'
      fullPath: '/api/public/meta-run-insights'
      preLoaderRoute: typeof ApiPublicMetaRunInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/liz-image': {
      id: '/api/public/liz-image'
      path: '/api/public/liz-image'
      fullPath: '/api/public/liz-image'
      preLoaderRoute: typeof ApiPublicLizImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/liz-chat': {
      id: '/api/public/liz-chat'
      path: '/api/public/liz-chat'
      fullPath: '/api/public/liz-chat'
      preLoaderRoute: typeof ApiPublicLizChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ensure-approved-login': {
      id: '/api/public/ensure-approved-login'
      path: '/api/public/ensure-approved-login'
      fullPath: '/api/public/ensure-approved-login'
      preLoaderRoute: typeof ApiPublicEnsureApprovedLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mod/saude': {
      id: '/_authenticated/mod/saude'
      path: '/mod/saude'
      fullPath: '/mod/saude'
      preLoaderRoute: typeof AuthenticatedModSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/responsaveis': {
      id: '/_authenticated/mod/responsaveis'
      path: '/mod/responsaveis'
      fullPath: '/mod/responsaveis'
      preLoaderRoute: typeof AuthenticatedModResponsaveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/ploomes-integracao': {
      id: '/_authenticated/mod/ploomes-integracao'
      path: '/mod/ploomes-integracao'
      fullPath: '/mod/ploomes-integracao'
      preLoaderRoute: typeof AuthenticatedModPloomesIntegracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/meta-debug': {
      id: '/_authenticated/mod/meta-debug'
      path: '/mod/meta-debug'
      fullPath: '/mod/meta-debug'
      preLoaderRoute: typeof AuthenticatedModMetaDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/meta-conversions': {
      id: '/_authenticated/mod/meta-conversions'
      path: '/mod/meta-conversions'
      fullPath: '/mod/meta-conversions'
      preLoaderRoute: typeof AuthenticatedModMetaConversionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/marketing': {
      id: '/_authenticated/mod/marketing'
      path: '/mod/marketing'
      fullPath: '/mod/marketing'
      preLoaderRoute: typeof AuthenticatedModMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/ia': {
      id: '/_authenticated/mod/ia'
      path: '/mod/ia'
      fullPath: '/mod/ia'
      preLoaderRoute: typeof AuthenticatedModIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/financeiro': {
      id: '/_authenticated/mod/financeiro'
      path: '/mod/financeiro'
      fullPath: '/mod/financeiro'
      preLoaderRoute: typeof AuthenticatedModFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/design-system': {
      id: '/_authenticated/mod/design-system'
      path: '/mod/design-system'
      fullPath: '/mod/design-system'
      preLoaderRoute: typeof AuthenticatedModDesignSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/chamados': {
      id: '/_authenticated/mod/chamados'
      path: '/mod/chamados'
      fullPath: '/mod/chamados'
      preLoaderRoute: typeof AuthenticatedModChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/bi': {
      id: '/_authenticated/mod/bi'
      path: '/mod/bi'
      fullPath: '/mod/bi'
      preLoaderRoute: typeof AuthenticatedModBiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/automacoes': {
      id: '/_authenticated/mod/automacoes'
      path: '/mod/automacoes'
      fullPath: '/mod/automacoes'
      preLoaderRoute: typeof AuthenticatedModAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/auditoria': {
      id: '/_authenticated/mod/auditoria'
      path: '/mod/auditoria'
      fullPath: '/mod/auditoria'
      preLoaderRoute: typeof AuthenticatedModAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/admin': {
      id: '/_authenticated/mod/admin'
      path: '/mod/admin'
      fullPath: '/mod/admin'
      preLoaderRoute: typeof AuthenticatedModAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mod/whatsapp/': {
      id: '/_authenticated/mod/whatsapp/'
      path: '/mod/whatsapp'
      fullPath: '/mod/whatsapp/'
      preLoaderRoute: typeof AuthenticatedModWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ploomes/webhook': {
      id: '/api/public/ploomes/webhook'
      path: '/api/public/ploomes/webhook'
      fullPath: '/api/public/ploomes/webhook'
      preLoaderRoute: typeof ApiPublicPloomesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ploomes/sync-users': {
      id: '/api/public/ploomes/sync-users'
      path: '/api/public/ploomes/sync-users'
      fullPath: '/api/public/ploomes/sync-users'
      preLoaderRoute: typeof ApiPublicPloomesSyncUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-sync': {
      id: '/api/public/hooks/meta-sync'
      path: '/api/public/hooks/meta-sync'
      fullPath: '/api/public/hooks/meta-sync'
      preLoaderRoute: typeof ApiPublicHooksMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mod/whatsapp/conhecimento': {
      id: '/_authenticated/mod/whatsapp/conhecimento'
      path: '/mod/whatsapp/conhecimento'
      fullPath: '/mod/whatsapp/conhecimento'
      preLoaderRoute: typeof AuthenticatedModWhatsappConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mod/whatsapp/config': {
      id: '/_authenticated/mod/whatsapp/config'
      path: '/mod/whatsapp/config'
      fullPath: '/mod/whatsapp/config'
      preLoaderRoute: typeof AuthenticatedModWhatsappConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/wa/queue/process': {
      id: '/api/public/wa/queue/process'
      path: '/api/public/wa/queue/process'
      fullPath: '/api/public/wa/queue/process'
      preLoaderRoute: typeof ApiPublicWaQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/audience/sync': {
      id: '/api/public/meta/audience/sync'
      path: '/api/public/meta/audience/sync'
      fullPath: '/api/public/meta/audience/sync'
      preLoaderRoute: typeof ApiPublicMetaAudienceSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/audience/qualified.csv': {
      id: '/api/public/meta/audience/qualified.csv'
      path: '/api/public/meta/audience/qualified.csv'
      fullPath: '/api/public/meta/audience/qualified.csv'
      preLoaderRoute: typeof ApiPublicMetaAudienceQualifiedDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/audience/customers.csv': {
      id: '/api/public/meta/audience/customers.csv'
      path: '/api/public/meta/audience/customers.csv'
      fullPath: '/api/public/meta/audience/customers.csv'
      preLoaderRoute: typeof ApiPublicMetaAudienceCustomersDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBaixarAppRoute: typeof AuthenticatedBaixarAppRoute
  AuthenticatedCoordenacaoRoute: typeof AuthenticatedCoordenacaoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLizStudioRoute: typeof AuthenticatedLizStudioRoute
  AuthenticatedMarketingHubRoute: typeof AuthenticatedMarketingHubRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedSdrLeadqualifiedRoute: typeof AuthenticatedSdrLeadqualifiedRoute
  AuthenticatedModAdminRoute: typeof AuthenticatedModAdminRoute
  AuthenticatedModAuditoriaRoute: typeof AuthenticatedModAuditoriaRoute
  AuthenticatedModAutomacoesRoute: typeof AuthenticatedModAutomacoesRoute
  AuthenticatedModBiRoute: typeof AuthenticatedModBiRoute
  AuthenticatedModChamadosRoute: typeof AuthenticatedModChamadosRoute
  AuthenticatedModDesignSystemRoute: typeof AuthenticatedModDesignSystemRoute
  AuthenticatedModFinanceiroRoute: typeof AuthenticatedModFinanceiroRoute
  AuthenticatedModIaRoute: typeof AuthenticatedModIaRoute
  AuthenticatedModMarketingRoute: typeof AuthenticatedModMarketingRoute
  AuthenticatedModMetaConversionsRoute: typeof AuthenticatedModMetaConversionsRoute
  AuthenticatedModMetaDebugRoute: typeof AuthenticatedModMetaDebugRoute
  AuthenticatedModPloomesIntegracaoRoute: typeof AuthenticatedModPloomesIntegracaoRoute
  AuthenticatedModResponsaveisRoute: typeof AuthenticatedModResponsaveisRoute
  AuthenticatedModSaudeRoute: typeof AuthenticatedModSaudeRoute
  AuthenticatedModIndexRoute: typeof AuthenticatedModIndexRoute
  AuthenticatedModWhatsappConfigRoute: typeof AuthenticatedModWhatsappConfigRoute
  AuthenticatedModWhatsappConhecimentoRoute: typeof AuthenticatedModWhatsappConhecimentoRoute
  AuthenticatedModWhatsappIndexRoute: typeof AuthenticatedModWhatsappIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBaixarAppRoute: AuthenticatedBaixarAppRoute,
  AuthenticatedCoordenacaoRoute: AuthenticatedCoordenacaoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLizStudioRoute: AuthenticatedLizStudioRoute,
  AuthenticatedMarketingHubRoute: AuthenticatedMarketingHubRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedSdrLeadqualifiedRoute: AuthenticatedSdrLeadqualifiedRoute,
  AuthenticatedModAdminRoute: AuthenticatedModAdminRoute,
  AuthenticatedModAuditoriaRoute: AuthenticatedModAuditoriaRoute,
  AuthenticatedModAutomacoesRoute: AuthenticatedModAutomacoesRoute,
  AuthenticatedModBiRoute: AuthenticatedModBiRoute,
  AuthenticatedModChamadosRoute: AuthenticatedModChamadosRoute,
  AuthenticatedModDesignSystemRoute: AuthenticatedModDesignSystemRoute,
  AuthenticatedModFinanceiroRoute: AuthenticatedModFinanceiroRoute,
  AuthenticatedModIaRoute: AuthenticatedModIaRoute,
  AuthenticatedModMarketingRoute: AuthenticatedModMarketingRoute,
  AuthenticatedModMetaConversionsRoute: AuthenticatedModMetaConversionsRoute,
  AuthenticatedModMetaDebugRoute: AuthenticatedModMetaDebugRoute,
  AuthenticatedModPloomesIntegracaoRoute:
    AuthenticatedModPloomesIntegracaoRoute,
  AuthenticatedModResponsaveisRoute: AuthenticatedModResponsaveisRoute,
  AuthenticatedModSaudeRoute: AuthenticatedModSaudeRoute,
  AuthenticatedModIndexRoute: AuthenticatedModIndexRoute,
  AuthenticatedModWhatsappConfigRoute: AuthenticatedModWhatsappConfigRoute,
  AuthenticatedModWhatsappConhecimentoRoute:
    AuthenticatedModWhatsappConhecimentoRoute,
  AuthenticatedModWhatsappIndexRoute: AuthenticatedModWhatsappIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprovarUsuarioRoute: AprovarUsuarioRoute,
  AuthRoute: AuthRoute,
  CapturaRoute: CapturaRoute,
  McpRoute: McpRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WppRoute: WppRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEnsureApprovedLoginRoute: ApiPublicEnsureApprovedLoginRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicLizChatRoute: ApiPublicLizChatRoute,
  ApiPublicLizImageRoute: ApiPublicLizImageRoute,
  ApiPublicMetaRunInsightsRoute: ApiPublicMetaRunInsightsRoute,
  ApiPublicNotifyApprovalRoute: ApiPublicNotifyApprovalRoute,
  ApiPublicTestApprovalEmailRoute: ApiPublicTestApprovalEmailRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksMetaSyncRoute: ApiPublicHooksMetaSyncRoute,
  ApiPublicPloomesSyncUsersRoute: ApiPublicPloomesSyncUsersRoute,
  ApiPublicPloomesWebhookRoute: ApiPublicPloomesWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicMetaAudienceCustomersDotcsvRoute:
    ApiPublicMetaAudienceCustomersDotcsvRoute,
  ApiPublicMetaAudienceQualifiedDotcsvRoute:
    ApiPublicMetaAudienceQualifiedDotcsvRoute,
  ApiPublicMetaAudienceSyncRoute: ApiPublicMetaAudienceSyncRoute,
  ApiPublicWaQueueProcessRoute: ApiPublicWaQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
